/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"

int *
helloworld_1_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	static char hello[256] = "Hello Suranga....";
	static char*hello1;

	printf("Entering the server.......\n");
	hello1 = hello;
	printf("Returning from the server()\n" );

	return(&hello1);
}
