/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"


void
helloworldprog_1( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	char*  helloworld_1_arg;

	clnt = clnt_create(host, HELLOWORLDPROG, HELLOWORLDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = helloworld_1((void*)&helloworld_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}



printf("Got\"%s\"from the server\n",result_1);


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	helloworldprog_1( host );
}
