/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define HELLOWORLDPROG ((rpc_uint)1234567)
#define HELLOWORLDVERS ((rpc_uint)1)

#ifdef __cplusplus
#define HELLOWORLD ((rpc_uint)1)
extern "C" int * helloworld_1(void *, CLIENT *);
extern "C" int * helloworld_1_svc(void *, struct svc_req *);

#elif __STDC__
#define HELLOWORLD ((rpc_uint)1)
extern  int * helloworld_1(void *, CLIENT *);
extern  int * helloworld_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define HELLOWORLD ((rpc_uint)1)
extern  int * helloworld_1();
extern  int * helloworld_1_svc();
#endif /* Old Style C */

#endif /* !_HELLO_H_RPCGEN */
